version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tripmate_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tripmate_user
      POSTGRES_PASSWORD: tripmate_password
      POSTGRES_DB: tripmate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}