# docker-compose.prod.yml
version: '3.8'

services:
  app:
    build: .
    container_name: tripmate_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
    depends_on:
      - postgres
    networks:
      - tripmate-network

networks:
  tripmate-network:
    driver: bridge

volumes:
  postgres_data_prod: