[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run prisma:generate",
    "npm run build",
    "ls -la",
    "ls -la dist/"
]

[start]
cmd = "npm run start:migrate:prod"